DefaultContentLanguage = "en"
author = "Anonymous"
baseURL = "/"
copyright = ""
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "casper3"
title = "Home"
[[menu.main]]
identifier = "Math"
name = "Math"
url = "/math/"
weight = 10
[[menu.main]]
identifier = "QF"
name = "QF"
url = "/QF/"
weight = 10
[[menu.main]]
identifier = "Econ"
name = "Econ"
url = "/econ/"
weight = 10
[[menu.main]]
identifier = "Data Science"
name = "Data Science"
url = "/Data-Science/"
weight = 10
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "Projects"
name = "Projects"
url = "/Projects/"
weight = 10
[[menu.main]]
identifier = "Articles"
name = "Articles"
url = "/Articles/"
weight = 10
[[menu.main]]
identifier = "Books"
name = "Books"
url = "/books/"
weight = 10
[params]
description = "Processing Stochasticities"
facebook = ""
github = "https://github.com/joshuapurtell"
logo = "/images/test_logo.png"
mainSections = ["math", "post"]
twitter = "https://twitter.com/quantumwitty"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
