DefaultContentLanguage = "en"
author = "Anonymous"
baseURL = "/"
copyright = ""
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "casper3"
title = "Hugo Themes"
[[menu.main]]
identifier = "Math"
name = "Math"
url = "\"/math/\""
weight = 10
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[params]
description = "Processing Stochasticities"
facebook = ""
github = "https://github.com/joshuapurtell"
logo = "/images/test_logo.png"
mainSections = ["Math", "post"]
twitter = "https://twitter.com"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
